### ISSUE TITLE
Importing of roles from contentful-export script

### ISSUE THREAD

**Issue by msalpietro** [contentful/contentful-batch-libs#104]
Push-to-space does not create roles that are included in contentful-export json output file.

**Comment by Khaledgarbaya** [comment]
Hi @msalpietro,
Thank you for the issue and the PR. The main reason we didn't add the roles import yet is that every space has by default some roles and we'll end up with duplicate roles in the destination space.
I will check once again with the product team and get back to you asap.
Meanwhile, if there is a need for importing the roles for you workflow please feel free to use the fork you made.
Best,
Khaled

**Comment by msalpietro** [comment]
Makes sense. I add a separate function for Roles to check for existing name instead of id for update as those need to be unique. Found another issue with the management SDK, it has a createRoleWithId function on the Space entity, which was throwing me an internal server error. API documentation states you can't create a role with a custom ID using put however.

**Comment by Khaledgarbaya** [comment]
hmm I will check that asap

**Comment by marcolink** [comment]
closing this since it's outdated
