### ISSUE TITLE
includeDrafts is ignored for Assets (drafts are returned, but shouldn't)

### ISSUE THREAD

**Issue by rmehner** [contentful/contentful-batch-libs#147]
:wave:

I was using [contentful-export](https://github.com/contentful/contentful-export) and did not want to include drafts. That works just fine for content, but not for assets. Looking at the code, it's kinda obvious, why:

For content-types there's code to filter the drafts, based on the setting: https://github.com/contentful/contentful-batch-libs/blob/6420238e57bcec36f959128bdce26ff8a377b051/lib/get/get-full-source-space.js#L73

There is no code to do the same for assets:
https://github.com/contentful/contentful-batch-libs/blob/6420238e57bcec36f959128bdce26ff8a377b051/lib/get/get-full-source-space.js#L94-L98

I was under the impression that when I don't want to include drafts, it also applies to assets, but maybe I'm understanding something wrong. So is that a bug / oversight, or is there a reasoning behind it?

My use case is exporting / importing content & assets, but I ran into validation errors because there was a draft asset lingering around.

Thanks for reading and have a great day!

**Comment by axe312ger** [comment]
Hey there Robin,

thank you for this bug report. You are right, this is mistake and it actually should skip the assets. I put it on our internal todo list for the next upcoming version :)

All the best,
Benedikt

**Comment by Khaledgarbaya** [comment]
Hi @rmehner a fix will be released in the `@next` version soon

**Comment by rmehner** [comment]
@Khaledgarbaya neat :) I don't use this anymore, but it's nice to see it fixed. Good work all around!

**Comment by Khaledgarbaya** [comment]
Fixed in https://github.com/contentful/contentful-export/pull/101
