### ISSUE TITLE
Breaking Node Version Update Added in 9.5.1 Patch

### ISSUE THREAD

**Issue by aaronhargrove-grub** [contentful/contentful-batch-libs#217]
Release 9.5.1 dropped support for [all node versions below 18](https://github.com/contentful/contentful-batch-libs/compare/v9.5.0...v9.5.1#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R8). However, this was done in a patch release, which breaks all consumers who that are currently on a semver that is supposed to support those older versions. It doesn't leave the option for Node 16 consumers to stay on the current contentful version until they are able to upgrade to Node 18, and then upgrade to a new version of the package that targets Node 18. These breaking changes should really be done in a major release.

Same thing happened in https://github.com/contentful/contentful-export/issues/1526

[Pull request](https://github.com/contentful/contentful-batch-libs/pull/194) which calls out that it is a breaking change

**Comment by marcolink** [comment]
@aaronhargrove-grub Sorry to hear that this caused an issue on your side. This wasn't released as planned. I agree that changes to the min node version should be reflected as breaking change.
