### ISSUE TITLE
Broken handling of skipContentModel in getFullSourceSpace

### ISSUE THREAD

**Issue by felixjung** [contentful/contentful-batch-libs#79]
Hi,

I'm trying to build something with these libs. When using `getFullSourceSpace` with option `skipContentModel` set to `true` I encountered the following error:

``` bash
info Getting content from source space
(node:24538) UnhandledPromiseRejectionWarning: Unhandled
promise rejection (rejection id: 1): TypeError: Cannot read property 'filter' of undefined
```

Looking at the code I believe this to be due to [lines #39-41](https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-full-source-space.js#L39-L41):

``` javascript
response.editorInterfaces = response.editorInterfaces.filter((editorInterface) => {
  return editorInterface !== null
})
```

In the preceding callback, `response.editorInterfaces` is only set if `response.contentTypes.length !==  0`. Thus, when `response.contentType.length === 0`, the call to `response.editorInterfaces.filter` fails, because `response.editorInterFaces` is `undefined`.

I don't know what the editor interfaces are being used for and whether it would make more sense to remove the condition on setting the property. After all, this code in [lines #55-64](https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-full-source-space.js#L55-64)

```javascript
function getEditorInterfaces (contentTypes) {
  const editorInterfacePromises = contentTypes.map((contentType) => {
    // old contentTypes may not have an editor interface but we'll handle in a later stage
    // but it should not stop getting the data process
    return contentType.getEditorInterface().catch(() => {
      return Promise.resolve(null)
    })
  })
  return Promise.all(editorInterfacePromises)
}
```

 will simply return a promise resolving to an empty array. Right? My gut feeling tells me

```javascript

  return managementClient.getSpace(spaceId)
  .then((space) => {
    return Promise.props({
      contentTypes: skipContentModel ? [] : pagedGet(space, 'getContentTypes').then(extractItems),
      entries: skipContent ? [] : pagedGet(deliveryClient || space, 'getEntries').then(extractItems),
      assets: skipContent ? [] : pagedGet(space, 'getAssets').then(extractItems),
      locales: skipContentModel ? [] : pagedGet(space, 'getLocales').then(extractItems),
      webhooks: skipWebhooks ? [] : pagedGet(space, 'getWebhooks').then(extractItems),
      roles: skipRoles ? [] : pagedGet(space, 'getRoles').then(extractItems)
    }).then((response) => {
      response.editorInterfaces = getEditorInterfaces(response.contentTypes)
      return Promise.props(response)
    }).then((response) => {
      response.editorInterfaces = response.editorInterfaces.filter((editorInterface) => {
        return editorInterface !== null
      })
      return response
    })
  }, (err) => {
    log.error(`
The destination space was not found. This can happen for multiple reasons:
- If you haven't yet, you should create your space manually.
- If your destination space is in another organization, and your user from the source space does not have access to it, you'll need to specify separate sourceManagementToken and destinationManagementToken

Full error details below.
`)
    throw err
  })
```

should run just fine.

What do you think?

**Comment by Khaledgarbaya** [comment]
Hi @felixjung, the thing is some contentTypes may or may not have an editor interface. The bug here is that I forgot to set `response.editorInterfaces` to `[]`, I will push a fix right away

**Comment by Khaledgarbaya** [comment]
here is the commit : https://github.com/contentful/contentful-batch-libs/commit/35ee3f35fe8d162b612cd9300d9ab126a8070d15

**Comment by felixjung** [comment]
Hm yeah, I understand that. My point was just that instead of having any if clause at all, you could just run the `.map` call anyway. In code, I think
```javascript
.then((response) => {
  if (response.contentTypes.length !== 0) {
    response.editorInterfaces = getEditorInterfaces(response.contentTypes)
    return Promise.props(response)
  }
  response.editorInterfaces = []
  return response
})
```

and this

```javascript
.then((response) => {
  response.editorInterfaces = getEditorInterfaces(response.contentTypes)
  return Promise.props(response)
})
```

are essentially the same, because the call to `getEditorInterfaces()` will return a promise resolving to an empty array when `response.contentTypes` is `[]`, anyway. If I'm right, that would be cleaner, no?

**Comment by axe312ger** [comment]
@felixjung I agree with u but since we will refactor the logic in there in the near future and the actual bug was fixed in last December, I will close this ticket for now.

**Comment by iolloyd** [comment]
Is this still going to be addressed in 'the near future'?

**Comment by axe312ger** [comment]
> Is this still going to be addressed in 'the near future'?

Yes. Can't be more precise because there are high priorities at the moment, but that's very much on top of the list.

What are you missing @iolloyd? We are (sadly) no superheroes, every PR is welcome :)
