### ISSUE TITLE
Misleading error message in getFullSourceSpace (copy-paste?)

### ISSUE THREAD

**Issue by apaatsio** [contentful/contentful-batch-libs#81]
I was looking at the source code and noticed a weird error message.

The error message talks about *destination* space but we are dealing with *source* space here, right? See https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-full-source-space.js#L47-L49

I think this is just a copy-paste from https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-outdated-destination-content.js#L26-L28

**Comment by marcolink** [comment]
Closing this as it seems a bit outdated.
