### ISSUE TITLE
Draft handling in pushToSpace is wrong

### ISSUE THREAD

**Issue by felixjung** [contentful/contentful-batch-libs#83]
Hi,

As part of an investigation into a problem with entries not getting published anymore as part of `pushToSpace()` I discovered a problem with the drafts handling introduced by this [change](https://github.com/contentful/contentful-batch-libs/pull/82/files#diff-00fb918629568cde57c3b855bf8990b9R132) to `push-to-space.js` in #82. Specifically,

```
...
const drafts = sourceContent.entries.filter((entry) => entry.isDraft)
sourceContent.entries = sourceContent.entries.filter((entry) => !entry.isDraft)
result = result
  .then(partial(creation.createEntries,
    {space: space, skipContentModel: skipContentModel}, drafts, []))
...
```

At this stage `sourceContent.entries` is a collection of objects with just two properties: `original` and `transformed`. The first being the actual source space entry and the second being the output of the entry transform function. Hence, `entry.isDraft` is `undefined` in the filter predicate. Moreover, `isDraft` is a method of `Entry` and not a boolean. Even if the above code were correct and entry were the original entry, the current code would identify every entry as draft -- `entry.isDraft` would be truthy, because `isDraft` would be a method.

To fix this entire part I would suggest something along the lines of

``` javascript
const drafts = sourceContent.entries.filter(({original: entry}) => entry.isDraft())
const publishedEntries = sourceContent.entries.filter(({original: entry}) => !entry.isDraft())
```

I will open a PR with a fix, probably today. First I need to figure out why my entries are not getting published, though.

**Comment by Khaledgarbaya** [comment]
Hi @felixjung, Thanks a lot for the long explanation you are totally right, sorry about that

**Comment by felixjung** [comment]
Cool 😎 Happy to help 👍

**Comment by Khaledgarbaya** [comment]
@felixjung I wanna send you some swags can you send me your email kgarbaya[at]gmail.com
