### ISSUE TITLE
Enable async transforms

### ISSUE THREAD

**Issue by felixjung** [contentful/contentful-batch-libs#87]
Hey,

I'm looking to transform some of our content in a way that fields of a content type are converted into references to entries of a content type on the destination space. The referenced entries, however, don't exist on the destination space, yet. I would like to create them on-the- fly, if they don't exist.

Currently, the [corresponding code](https://github.com/contentful/contentful-batch-libs/blob/master/lib/transform/transform-space.js#L17-L26) in `transform-space.js` looks like it would support async operations within the transformer functions &mdash; good thing that TODO hasn't been investigated further, yet 😉.

What's missing, is a way to access the space's methods for interacting with content (e.g., access to `createEntry` etc.). To maintain API compatibility, I would propose a change along the lines of this:

```javascript
export default function (
  space, destinationSpace, customTransformers, entities = spaceEntities
) {
  const transformers = defaults(customTransformers, defaultTransformers)
  // TODO maybe we don't need promises here at all
  const newSpace = omit(space, ...entities)
  return Promise.reduce(entities, (newSpace, type) => {
    return Promise.map(
      space[type],
      (entity) => Promise.resolve(transformers[type](entity, destinationEntities, destinationSpace))
        .then(transformed => ({
        original: entity,
        transformed 
      }))
    )
      .then((entities) => {
        newSpace[type] = entities
        return newSpace
      })
  }, newSpace)
}
```

This should allow you to access `destinationSpace`'s methods, if an actual instance of `Space` from the management API client is provided to `transformSpace`. The transformer functions could interact with the space, this way. In addition because the entire destination space is now available within a transformer, transformers can now do things like creating references to other entity types (e.g., add a link to an asset in an entry).

I'd be willing to implement this and would also try to provide a cleaner solution than what I wrote down above.

@Khaledgarbaya, WDYT?

**Comment by Khaledgarbaya** [comment]
Thanks @felixjung I had plans around the transformatio,/ I am kinda busy right now, I will get back to you asap.

**Comment by felixjung** [comment]
Sure, right now I might not need this after all, anyway. Found a different solution. I guess this would still be helpful, though.

**Comment by marcolink** [comment]
closing this for now as there hasn't been any activity in a while.
