### ISSUE TITLE
batchedIdQuery inconsistent

### ISSUE THREAD

**Issue by aghuddleston** [contentful/contentful-batch-libs#89]
I've been working on my own export/import tool, using a lot of contentful-batch-libs.  One issue I'm seeing is with `getOutdatedDestinationContent` and the `batchedIdQuery`.  The ids are batched correctly, but not all the entries (or assets) are consistently found in the destination space.  But, if I query for each id individually, the entry/asset is returned.  I also experimented w/reducing the `BATCH_CHAR_LIMIT` and at some number lower than 1990, for me around 1200, the batches would find all the entries/assets.  

I'm running the getOutdatedDestinationContent process on 250 assets/entries at a time.

Any ideas why the inclusion query is dropping entries/assets?  Is reducing the `BATCH_CHAR_LIMIT` the best way to go?

Thanks for your feedback.

**Comment by Khaledgarbaya** [comment]
hi @aghuddleston ,
this is weird, I didn't have this issue before as you can see [here](https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-outdated-destination-content.js#L37) the response should contain all your entries.
Can you maybe provide a snippet of code where the problem happened ?

**Comment by aghuddleston** [comment]
I'm just calling https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-outdated-destination-content.js#L13 with an array of 250 asset ids.

It results in 2 batches, one with 157 ids and one with 93.  The response for the first batch has 100 assets from the destination and the second batch has 93.

I've run this numerous times on other sets of 250 ids, and it works fine.  But for this set, with `BATCH_CHAR_LIMIT` at 1990, it _always_ returns 193 assets instead of 250.

I can provide the space id and the asset ids if that is helpful.

**Comment by Khaledgarbaya** [comment]
@aghuddleston please don't share any information about the space here, feel free to create the a support ticket and give the information there. And I will take a look. for now if changing the `BATCH_CHAR_LIMIT` works for you feel free to change it locally and work with that untill I check the problem, but It will be tricky to reproduce the issue since it works with other spaces.

have you tried exporting the same space using [contentful-export](https://github.com/contentful/contentful-export)

**Comment by aghuddleston** [comment]
Will do, thanks. 

Yes, the contentful-export works fine, and the data I'm working with is actually from a call to https://github.com/contentful/contentful-batch-libs/blob/master/lib/get/get-full-source-space.js#L10

**Comment by Khaledgarbaya** [comment]
Ahh totally missed that, sorry can you try using that function instead ?

**Comment by aghuddleston** [comment]
Sorry, not following.  When I'm importing, I want to follow the approach you have for importing, to only get the supplied ids from the destination.  Getting the full destination space would _maybe_ work.  I'll have to think about.  But the space is getting larger which is why I'd prefer to only get the entries/assets I'm working w/at the moment.

**Comment by Khaledgarbaya** [comment]
Ok got your point, are all the assets you are trying to get published already?

**Comment by aghuddleston** [comment]
I have tried when the assets are published and not published.  Same result, either way.

**Comment by aghuddleston** [comment]
Support ticket created.  Thanks for your help.  Let me know if you need the ticket id.
